/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { UserProfile } from '../types';

export const TEST_PROFILES: Partial<UserProfile>[] = [
  {
    uid: 'test_ms05',
    fullName: 'Đặng Thanh Trà',
    birthYear: 2006,
    hometownVn: 'Nam Định',
    koreanRegion: 'Chungbuk',
    heightCm: 155,
    personality: 'Nghe kể chuyện - nghe nhạc',
    partnerPreference: 'Người Công giáo - Nam <2002 - Cao >1m55',
    gender: 'female',
    occupation: 'Sinh viên/Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS05. Nghe kể chuyện - nghe nhạc. Mong muốn tìm: Người Công giáo - Nam <2002 - Cao >1m55',
    hobbies: ['Nghe kể chuyện', 'Nghe nhạc'],
    avatarUrl: 'https://picsum.photos/seed/ms05/400/500',
    photoUrls: [],
    smoking: 'no',
    drinking: 'no',
    mbti: 'INFJ',
    religion: 'Công giáo',
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms16',
    fullName: 'Mỹ Liên',
    birthYear: 1997,
    hometownVn: 'Tây Ninh',
    koreanRegion: 'Gyeonggi-do',
    heightCm: 156,
    personality: 'Vui vẻ - chân thành - có trách nhiệm - xem phim',
    partnerPreference: 'Trưởng thành - nghiêm túc - không cờ bạc - Nam 1998~1999 - Cao >1m6',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS16. Vui vẻ - chân thành - có trách nhiệm - xem phim. Mong muốn tìm: Trưởng thành - nghiêm túc - không cờ bạc - Nam 1998~1999 - Cao >1m6',
    hobbies: ['Vui vẻ', 'Xem phim'],
    avatarUrl: 'https://picsum.photos/seed/ms16/400/500',
    photoUrls: [],
    smoking: 'no',
    drinking: 'sometimes',
    mbti: 'ENFJ',
    religion: 'Không',
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms17',
    fullName: 'Phương Thảo',
    birthYear: 2005,
    hometownVn: 'Hải Phòng',
    koreanRegion: 'Seoul',
    heightCm: 158,
    personality: 'Chụp ảnh - đi chơi',
    partnerPreference: 'Công việc ổn định - không cờ bạc - Nam 2000~2004 - Cao >1m7',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS17. Chụp ảnh - đi chơi. Mong muốn tìm: Công việc ổn định - không cờ bạc - Nam 2000~2004 - Cao >1m7',
    hobbies: ['Chụp ảnh', 'Đi chơi'],
    avatarUrl: 'https://picsum.photos/seed/ms17/400/500',
    photoUrls: [],
    smoking: 'sometimes',
    drinking: 'sometimes',
    mbti: 'ESFP',
    religion: 'Phật giáo',
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms21',
    fullName: 'Yến Nhi',
    birthYear: 2005,
    hometownVn: 'Quảng Ngãi',
    koreanRegion: 'Daejeon',
    heightCm: 154,
    personality: 'Nghe nhạc - thích hoa - hài hước - mê trái cây',
    partnerPreference: 'Tự lập kinh tế - ưa nhìn - chỉ yêu mình em - Nam 1999~2003 - Cao >1m65',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS21. Nghe nhạc - thích hoa - hài hước - mê trái cây. Mong muốn tìm: Tự lập kinh tế - ưa nhìn - chỉ yêu mình em - Nam 1999~2003 - Cao >1m65',
    hobbies: ['Nghe nhạc', 'Thích hoa'],
    avatarUrl: 'https://picsum.photos/seed/ms21/400/500',
    photoUrls: [],
    smoking: 'no',
    drinking: 'no',
    mbti: 'INFP',
    religion: 'Không',
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms25',
    fullName: 'Trần Minh',
    birthYear: 2001,
    hometownVn: 'Nghệ An',
    koreanRegion: 'Gimhae',
    heightCm: 165,
    personality: 'Đọc truyện',
    partnerPreference: 'Ngoại hình ưa nhìn - hòa đồng - Nam 1995~2000 - Cao >1m65',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS25. Đọc truyện. Mong muốn tìm: Ngoại hình ưa nhìn - hòa đồng - Nam 1995~2000 - Cao >1m65',
    hobbies: ['Đọc truyện'],
    avatarUrl: 'https://picsum.photos/seed/ms25/400/500',
    photoUrls: [],
    smoking: 'no',
    drinking: 'no',
    mbti: 'ISFJ',
    religion: 'Không',
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms26',
    fullName: 'Thanh PT',
    birthYear: 2003,
    hometownVn: 'Quảng Bình',
    koreanRegion: 'Mokpo',
    heightCm: 160,
    personality: 'Nghe nhạc - đi dạo',
    partnerPreference: 'Tìm hiểu nghiêm túc - cùng quê QB hoặc miền Trung - Nam 1996~2003 - Cao >1m65',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS26. Nghe nhạc - đi dạo. Mong muốn tìm: Tìm hiểu nghiêm túc - cùng quê QB hoặc miền Trung - Nam 1996~2003 - Cao >1m65',
    hobbies: ['Nghe nhạc', 'Đi dạo'],
    avatarUrl: 'https://picsum.photos/seed/ms26/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms33',
    fullName: 'Thanh Thảo',
    birthYear: 2006,
    hometownVn: 'Nghệ An',
    koreanRegion: 'Cheonan',
    heightCm: 150,
    personality: 'Mua sắm - đi chơi - nghe nhạc',
    partnerPreference: 'Công việc ổn định - không hút thuốc rượu bia - Nam 1996~2005 - Cao >1m65',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS33. Mua sắm - đi chơi - nghe nhạc. Mong muốn tìm: Công việc ổn định - không hút thuốc rượu bia - Nam 1996~2005 - Cao >1m65',
    hobbies: ['Mua sắm', 'Đi chơi', 'Nghe nhạc'],
    avatarUrl: 'https://picsum.photos/seed/ms33/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms38',
    fullName: 'Huỳnh Như',
    birthYear: 1998,
    hometownVn: 'Đồng Tháp',
    koreanRegion: 'Andong',
    heightCm: 163,
    personality: 'Hướng nội nhưng dễ hòa đồng - thích khám phá',
    partnerPreference: 'Công việc ổn định - không ăn chơi quá - Nam 1990~2000 - Cao >1m65',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS38. Hướng nội nhưng dễ hòa đồng - thích khám phá. Mong muốn tìm: Công việc ổn định - không ăn chơi quá - Nam 1990~2000 - Cao >1m65',
    hobbies: ['Khám phá'],
    avatarUrl: 'https://picsum.photos/seed/ms38/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms42',
    fullName: 'Minh Anh',
    birthYear: 2006,
    hometownVn: 'Tây Ninh',
    koreanRegion: 'Seoul',
    heightCm: 170,
    personality: 'Trầm tính - ít nói - gặp đúng người sẽ dễ mở lòng',
    partnerPreference: 'Sinh sống tại Seoul - ít nhậu - công việc ổn định - Nam 1990~2000 - Cao 1m75',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS42. Trầm tính - ít nói - gặp đúng người sẽ dễ mở lòng. Mong muốn tìm: Sinh sống tại Seoul - ít nhậu - công việc ổn định - Nam 1990~2000 - Cao 1m75',
    hobbies: ['Trầm tính'],
    avatarUrl: 'https://picsum.photos/seed/ms42/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms43',
    fullName: 'Cẩm Tú',
    birthYear: 2005,
    hometownVn: 'Nghệ An',
    koreanRegion: 'Iksan',
    heightCm: 165,
    personality: 'Vui vẻ - dễ bị ảnh hưởng cảm xúc - thích nấu ăn',
    partnerPreference: 'Hợp pháp - ổn định - đủ trưởng thành làm chỗ dựa - Nam 1999~2003 - Cao 1m70',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS43. Vui vẻ - dễ bị ảnh hưởng cảm xúc - thích nấu ăn. Mong muốn tìm: Hợp pháp - ổn định - đủ trưởng thành làm chỗ dựa - Nam 1999~2003 - Cao 1m70',
    hobbies: ['Nấu ăn'],
    avatarUrl: 'https://picsum.photos/seed/ms43/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms51',
    fullName: 'Thảo Anh',
    birthYear: 2005,
    hometownVn: 'Nghệ An',
    koreanRegion: 'Gimhae',
    heightCm: 160,
    personality: 'Thích đi biển',
    partnerPreference: 'Ưa nhìn - hợp pháp - quê miền Trung (Thanh Hóa) - Nam 2000~2004 - Cao 1m70',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS51. Thích đi biển. Mong muốn tìm: Ưa nhìn - hợp pháp - quê miền Trung (Thanh Hóa) - Nam 2000~2004 - Cao 1m70',
    hobbies: ['Đi biển'],
    avatarUrl: 'https://picsum.photos/seed/ms51/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms53',
    fullName: 'Hồng Nhung',
    birthYear: 2000,
    hometownVn: 'Hà Nội',
    koreanRegion: 'Gwangju',
    heightCm: 155,
    personality: 'Hiền lành - sống tình cảm - chung thủy - xem phim',
    partnerPreference: 'Công việc ổn định - ưu tiên trai Hà Nội - không hút thuốc - Nam 1995~2000 - Cao 1m65',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS53. Hiền lành - sống tình cảm - chung thủy - xem phim. Mong muốn tìm: Công việc ổn định - ưu tiên trai Hà Nội - không hút thuốc - Nam 1995~2000 - Cao 1m65',
    hobbies: ['Xem phim'],
    avatarUrl: 'https://picsum.photos/seed/ms53/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms54',
    fullName: 'Huyền Trang',
    birthYear: 2002,
    hometownVn: 'Hải Dương',
    koreanRegion: 'Seoul',
    heightCm: 168,
    personality: 'Du lịch - xem phim - nghe nhạc',
    partnerPreference: 'Ưu tiên trai Bắc - thật thà - biết quan tâm - hợp pháp - Nam 1994~2002 - Cao 1m75',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS54. Du lịch - xem phim - nghe nhạc. Mong muốn tìm: Ưu tiên trai Bắc - thật thà - biết quan tâm - hợp pháp - Nam 1994~2002 - Cao 1m75',
    hobbies: ['Du lịch', 'Xem phim', 'Nghe nhạc'],
    avatarUrl: 'https://picsum.photos/seed/ms54/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms55',
    fullName: 'Trần Huyền',
    birthYear: 2001,
    hometownVn: 'Hưng Yên',
    koreanRegion: 'Daegu',
    heightCm: 158,
    personality: 'Đi cafe - xem phim - ngắm cảnh - đọc sách',
    partnerPreference: 'Chiều người yêu - vui vẻ - tử tế - cùng quê hoặc miền Bắc - Nam 1996~2003 - Cao 1m70',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS55. Đi cafe - xem phim - ngắm cảnh - đọc sách. Mong muốn tìm: Chiều người yêu - vui vẻ - tử tế - cùng quê hoặc miền Bắc - Nam 1996~2003 - Cao 1m70',
    hobbies: ['Đi cafe', 'Xem phim', 'Ngắm cảnh'],
    avatarUrl: 'https://picsum.photos/seed/ms55/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms56',
    fullName: 'Nguyễn Thơm',
    birthYear: 2003,
    hometownVn: 'Bắc Ninh',
    koreanRegion: 'Cheonan',
    heightCm: 156,
    personality: 'Tập gym - nghe nhạc - thích bận rộn - du lịch',
    partnerPreference: 'Quê miền Bắc - biết cách ăn mặc - ưa nhìn - trưởng thành - Nam 1990~2003 - Cao 1m70',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS56. Tập gym - nghe nhạc - thích bận rộn - du lịch. Mong muốn tìm: Quê miền Bắc - biết cách ăn mặc - ưa nhìn - trưởng thành - Nam 1990~2003 - Cao 1m70',
    hobbies: ['Tập gym', 'Nghe nhạc', 'Du lịch'],
    avatarUrl: 'https://picsum.photos/seed/ms56/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms58',
    fullName: 'Hân Nhi',
    birthYear: 2001,
    hometownVn: 'Hà Tĩnh',
    koreanRegion: 'Suncheon',
    heightCm: 150,
    personality: 'Hướng nội - nhẹ nhàng - gì cũng thích - dễ nuôi',
    partnerPreference: 'Ổn định công việc - có xe đi lại thì tốt - hướng ngoại - Nam 199X~2003 - Cao 1m65',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS58. Hướng nội - nhẹ nhàng - gì cũng thích - dễ nuôi. Mong muốn tìm: Ổn định công việc - có xe đi lại thì tốt - hướng ngoại - Nam 199X~2003 - Cao 1m65',
    hobbies: ['Nhẹ nhàng'],
    avatarUrl: 'https://picsum.photos/seed/ms58/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms59',
    fullName: 'Mai Uyên',
    birthYear: 2004,
    hometownVn: 'Hà Nam',
    koreanRegion: 'Daegu',
    heightCm: 165,
    personality: 'Single mom - mạnh mẽ nhưng vẫn cần được thương',
    partnerPreference: 'Tử tế - ưa nhìn - thật lòng thương em - Nam 199X~2004 - Cao >1m68',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS59. Single mom - mạnh mẽ nhưng vẫn cần được thương. Mong muốn tìm: Tử tế - ưa nhìn - thật lòng thương em - Nam 199X~2004 - Cao >1m68',
    hobbies: ['Mạnh mẽ'],
    avatarUrl: 'https://picsum.photos/seed/ms59/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms60',
    fullName: 'Nhàn',
    birthYear: 2001,
    hometownVn: 'Quảng Ninh',
    koreanRegion: 'Incheon',
    heightCm: 150,
    personality: 'Vui vẻ - dễ gần - đi lịch - mê biển - chụp hình',
    partnerPreference: 'Thích gu gầy - quê miền Bắc - Nam 1996~2003 - Cao >1m60',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS60. Vui vẻ - dễ gần - đi lịch - mê biển - chụp hình. Mong muốn tìm: Thích gu gầy - quê miền Bắc - Nam 1996~2003 - Cao >1m60',
    hobbies: ['Đi du lịch', 'Mê biển', 'Chụp hình'],
    avatarUrl: 'https://picsum.photos/seed/ms60/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms61',
    fullName: 'Trang',
    birthYear: 2005,
    hometownVn: 'Hà Nội',
    koreanRegion: 'Seoul',
    heightCm: 167,
    personality: 'Thân thiện - hòa đồng - thích ngủ',
    partnerPreference: 'Không hút thuốc - miền Bắc - Nam 1998~2004 - Cao 1m70',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS61. Thân thiện - hòa đồng - thích ngủ. Mong muốn tìm: Không hút thuốc - miền Bắc - Nam 1998~2004 - Cao 1m70',
    hobbies: ['Thích ngủ'],
    avatarUrl: 'https://picsum.photos/seed/ms61/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms62',
    fullName: 'Phương',
    birthYear: 1999,
    hometownVn: 'Hưng Yên',
    koreanRegion: 'Iksan',
    heightCm: 155,
    personality: 'Hòa đồng - vui vẻ - hoạt bát - nấu ăn - leo núi',
    partnerPreference: 'Trai miền Bắc VN - có thể cùng đồng hành - chia sẻ - Nam 1990~1998 - Cao 1m65',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS62. Hòa đồng - vui vẻ - hoạt bát - nấu ăn - leo núi. Mong muốn tìm: Trai miền Bắc VN - có thể cùng đồng hành - chia sẻ - Nam 1990~1998 - Cao 1m65',
    hobbies: ['Nấu ăn', 'Leo núi'],
    avatarUrl: 'https://picsum.photos/seed/ms62/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms63',
    fullName: 'Hằng',
    birthYear: 2000,
    hometownVn: 'Sài Gòn',
    koreanRegion: 'Suwon',
    heightCm: 160,
    personality: 'D2 (Thạc sĩ) - hòa đồng - hoạt bát - dễ cảm thông',
    partnerPreference: 'Công việc ổn định - nghiêm túc - có trách nhiệm - Nam 1995~2001 - Cao 1m60',
    gender: 'female',
    occupation: 'Sinh viên',
    datingGoal: 'serious',
    bio: 'Mã số: MS63. D2 (Thạc sĩ) - hòa đồng - hoạt bát - dễ cảm thông. Mong muốn tìm: Công việc ổn định - nghiêm túc - có trách nhiệm - Nam 1995~2001 - Cao 1m60',
    hobbies: ['Hòa đồng'],
    avatarUrl: 'https://picsum.photos/seed/ms63/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms64',
    fullName: 'Chinh',
    birthYear: 2006,
    hometownVn: 'Thanh Hóa',
    koreanRegion: 'Daegu',
    heightCm: 170,
    personality: 'Cung Bọ Cạp - thẳng tính - biết nghe lời',
    partnerPreference: 'Chỉ cần yêu chiều em là đủ - Nam 1996~2006 - Cao 1m70',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS64. Cung Bọ Cạp - thẳng tính - biết nghe lời. Mong muốn tìm: Chỉ cần yêu chiều em là đủ - Nam 1996~2006 - Cao 1m70',
    hobbies: ['Nghe lời'],
    avatarUrl: 'https://picsum.photos/seed/ms64/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms66',
    fullName: 'Giang',
    birthYear: 2000,
    hometownVn: 'Sài Gòn',
    koreanRegion: 'Seoul',
    heightCm: 154,
    personality: 'Hòa đồng - vui vẻ - thích chụp ảnh - ở nhà',
    partnerPreference: 'Quê quán miền Nam - Nam 1992~2001 - Cao 1m65',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS66. Hòa đồng - vui vẻ - thích chụp ảnh - ở nhà. Mong muốn tìm: Quê quán miền Nam - Nam 1992~2001 - Cao 1m65',
    hobbies: ['Chụp ảnh'],
    avatarUrl: 'https://picsum.photos/seed/ms66/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms67',
    fullName: 'Hiền',
    birthYear: 1997,
    hometownVn: 'Quảng Ninh',
    koreanRegion: 'Ansan',
    heightCm: 150,
    personality: 'Hiền lành - trầm tính - thoải mái bộc lộ cảm xúc',
    partnerPreference: 'Ưu tiên chịu khó - có chí tiến thủ - không bạo lực - Nam 1988~1998 - Cao 1m65',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS67. Hiền lành - trầm tính - thoải mái bộc lộ cảm xúc. Mong muốn tìm: Ưu tiên chịu khó - có chí tiến thủ - không bạo lực - Nam 1988~1998 - Cao 1m65',
    hobbies: ['Trầm tính'],
    avatarUrl: 'https://picsum.photos/seed/ms67/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms68',
    fullName: 'Giang',
    birthYear: 2002,
    hometownVn: 'Sài Gòn',
    koreanRegion: 'Masan',
    heightCm: 163,
    personality: 'Nhẹ nhàng - hòa đồng - vui vẻ - chơi game',
    partnerPreference: 'Tử tế - vui vẻ - trưởng thành - tôn trọng đối phương - Nam 1995~2001 - Cao 1m70',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS68. Nhẹ nhàng - hòa đồng - vui vẻ - chơi game. Mong muốn tìm: Tử tế - vui vẻ - trưởng thành - tôn trọng đối phương - Nam 1995~2001 - Cao 1m70',
    hobbies: ['Chơi game'],
    avatarUrl: 'https://picsum.photos/seed/ms68/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms70',
    fullName: 'Thanh',
    birthYear: 2001,
    hometownVn: 'Hải Phòng',
    koreanRegion: 'Cheongju',
    heightCm: 156,
    personality: 'Hướng nội - hay suy nghĩ - sống tình cảm',
    partnerPreference: 'Vui vẻ hòa đồng - biết quan tâm - ở miền Trung Hàn Quốc - Nam 1997~2002 - Cao 1m70',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS70. Hướng nội - hay suy nghĩ - sống tình cảm. Mong muốn tìm: Vui vẻ hòa đồng - biết quan tâm - ở miền Trung Hàn Quốc - Nam 1997~2002 - Cao 1m70',
    hobbies: ['Sống tình cảm'],
    avatarUrl: 'https://picsum.photos/seed/ms70/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms71',
    fullName: 'Triệu Thanh',
    birthYear: 1994,
    hometownVn: 'Hà Nội',
    koreanRegion: 'Cheongju',
    heightCm: 150,
    personality: 'Hướng ngoại - vui vẻ - dễ gần - đi du lịch',
    partnerPreference: 'Biết yêu thương - quan tâm người yêu - luôn ưu tiên em - Nam 1988~1996 - Cao 1m65',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS71. Hướng ngoại - vui vẻ - dễ gần - đi du lịch. Mong muốn tìm: Biết yêu thương - quan tâm người yêu - luôn ưu tiên em - Nam 1988~1996 - Cao 1m65',
    hobbies: ['Đi du lịch'],
    avatarUrl: 'https://picsum.photos/seed/ms71/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms72',
    fullName: 'Phương',
    birthYear: 1999,
    hometownVn: 'Sài Gòn',
    koreanRegion: 'Seongnam',
    heightCm: 150,
    personality: 'Hướng nội nhưng đủ thân thì hướng ngoại',
    partnerPreference: 'Công việc ổn định - ấm áp - trưởng thành - không cờ bạc - Nam 1992~1999 - Cao 1m67',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS72. Hướng nội nhưng đủ thân thì hướng ngoại. Mong muốn tìm: Công việc ổn định - ấm áp - trưởng thành - không cờ bạc - Nam 1992~1999 - Cao 1m67',
    hobbies: ['Hướng nội'],
    avatarUrl: 'https://picsum.photos/seed/ms72/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms75',
    fullName: 'Tâm',
    birthYear: 1999,
    hometownVn: 'Thanh Hóa',
    koreanRegion: 'Chưa rõ',
    heightCm: 155,
    personality: 'Hướng nội - nhẹ nhàng - đáng yêu',
    partnerPreference: 'Trưởng thành - nghiêm túc - hợp sẽ cưới - Nam 1990~2000 - Cao 1m65',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS75. Hướng nội - nhẹ nhàng - đáng yêu. Mong muốn tìm: Trưởng thành - nghiêm túc - hợp sẽ cưới - Nam 1990~2000 - Cao 1m65',
    hobbies: ['Nhẹ nhàng'],
    avatarUrl: 'https://picsum.photos/seed/ms75/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms76',
    fullName: 'Thao',
    birthYear: 1997,
    hometownVn: 'Kiên Giang',
    koreanRegion: 'Ulsan',
    heightCm: 163,
    personality: 'Sở thích nghe nhạc - xem phim - chơi game',
    partnerPreference: 'Ngoại hình ưa nhìn - hoạt bát - hiền - nghiêm túc - Nam 1990~2000 - Cao >1m65',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS76. Sở thích nghe nhạc - xem phim - chơi game. Mong muốn tìm: Ngoại hình ưa nhìn - hoạt bát - hiền - nghiêm túc - Nam 1990~2000 - Cao >1m65',
    hobbies: ['Nghe nhạc', 'Xem phim', 'Chơi game'],
    avatarUrl: 'https://picsum.photos/seed/ms76/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms78',
    fullName: 'Duyên',
    birthYear: 2002,
    hometownVn: 'Hải Phòng',
    koreanRegion: 'Gyeongju',
    heightCm: 152,
    personality: 'Hướng lung tung - thích dạo chill chill buổi tối',
    partnerPreference: 'Biết yêu thương chiều chuộng - công việc ổn định - Nam 1994~2004 - Cao 1m65',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS78. Hướng lung tung - thích dạo chill chill buổi tối. Mong muốn tìm: Biết yêu thương chiều chuộng - công việc ổn định - Nam 1994~2004 - Cao 1m65',
    hobbies: ['Dạo phố'],
    avatarUrl: 'https://picsum.photos/seed/ms78/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms79',
    fullName: 'Hằng',
    birthYear: 1998,
    hometownVn: 'Hải Phòng',
    koreanRegion: 'Cheonan',
    heightCm: 153,
    personality: 'Hơi hướng nội - nhẹ nhàng - xem phim - nghe nhạc',
    partnerPreference: 'Công việc ổn định - biết quan tâm - không hút thuốc - Nam 1988~2000 - Cao >1m65',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS79. Hơi hướng nội - nhẹ nhàng - xem phim - nghe nhạc. Mong muốn tìm: Công việc ổn định - biết quan tâm - không hút thuốc - Nam 1988~2000 - Cao >1m65',
    hobbies: ['Xem phim', 'Nghe nhạc'],
    avatarUrl: 'https://picsum.photos/seed/ms79/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms80',
    fullName: 'Trang',
    birthYear: 2001,
    hometownVn: 'Hà Nội',
    koreanRegion: 'Incheon',
    heightCm: 158,
    personality: 'Vui vẻ - hướng ngoại - du lịch - cafe - chụp ảnh',
    partnerPreference: 'Visa hợp pháp - công việc ổn định - biết chiều em xíu - Nam 1993~2001 - Cao 1m70',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS80. Vui vẻ - hướng ngoại - du lịch - cafe - chụp ảnh. Mong muốn tìm: Visa hợp pháp - công việc ổn định - biết chiều em xíu - Nam 1993~2001 - Cao 1m70',
    hobbies: ['Du lịch', 'Cafe', 'Chụp ảnh'],
    avatarUrl: 'https://picsum.photos/seed/ms80/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms81',
    fullName: 'Thùy',
    birthYear: 2001,
    hometownVn: 'Quảng Ninh',
    koreanRegion: 'Ulsan',
    heightCm: 156,
    personality: 'Dễ gần - thân thiện - thẳng tính nhưng thích làm nũng',
    partnerPreference: 'Công việc gọn gàng - ổn định - ấm áp - biết chăm sóc - Nam 1993~2001 - Cao 1m70',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS81. Dễ gần - thân thiện - thẳng tính nhưng thích làm nũng. Mong muốn tìm: Công việc gọn gàng - ổn định - ấm áp - biết chăm sóc - Nam 1993~2001 - Cao 1m70',
    hobbies: ['Dễ gần'],
    avatarUrl: 'https://picsum.photos/seed/ms81/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms82',
    fullName: 'Hương',
    birthYear: 2004,
    hometownVn: 'Hải Phòng',
    koreanRegion: 'Gunpo',
    heightCm: 160,
    personality: 'Ngoan - dễ thương - vui tính - lắp mô hình',
    partnerPreference: 'Công việc hợp pháp - ổn định là được - Nam 1995~2005 - Cao 1m70',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS82. Ngoan - dễ thương - vui tính - lắp mô hình. Mong muốn tìm: Công việc hợp pháp - ổn định là được - Nam 1995~2005 - Cao 1m70',
    hobbies: ['Lắp mô hình'],
    avatarUrl: 'https://picsum.photos/seed/ms82/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms83',
    fullName: 'Mi',
    birthYear: 1986,
    hometownVn: 'Sài Gòn',
    koreanRegion: 'Seoul',
    heightCm: 165,
    personality: 'Nghe ca nhạc - đi du lịch khám phá - đi dạo',
    partnerPreference: 'Điềm đạm - biết quan tâm - không gia trưởng - Nam 1981~1989 - Cao 1m70',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS83. Nghe ca nhạc - đi du lịch khám phá - đi dạo. Mong muốn tìm: Điềm đạm - biết quan tâm - không gia trưởng - Nam 1981~1989 - Cao 1m70',
    hobbies: ['Nghe nhạc', 'Du lịch'],
    avatarUrl: 'https://picsum.photos/seed/ms83/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
  {
    uid: 'test_ms84',
    fullName: 'Nhím',
    birthYear: 1990,
    hometownVn: 'Hà Tĩnh',
    koreanRegion: 'Gimhae',
    heightCm: 160,
    personality: 'Nấu ăn - làm bánh',
    partnerPreference: 'Không hút thuốc - không bụng bia - không keo kiệt - Nam 198X~199X - Cao 1m67',
    gender: 'female',
    occupation: 'Người lao động',
    datingGoal: 'serious',
    bio: 'Mã số: MS84. Nấu ăn - làm bánh. Mong muốn tìm: Không hút thuốc - không bụng bia - không keo kiệt - Nam 198X~199X - Cao 1m67',
    hobbies: ['Nấu ăn', 'Làm bánh'],
    avatarUrl: 'https://picsum.photos/seed/ms84/400/500',
    photoUrls: [],
    approvalStatus: 'approved',
    submittedAt: new Date().toISOString(),
    approvedAt: new Date().toISOString(),
  },
];
